errnorecname.v:9: unknown record: '__t_vtable0'
